using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SoulMemory.DarkSouls1
{
    public enum Area
    {
        Depths1BeginningOfLevel                                  = 100000   ,
        Depths2NearBonfireKey                                    = 100001   ,
        Depths3NearChanneler                                     = 100010   ,
        Depths4BlighttownDoor                                    = 100011   ,
        UndeadBurg1OutsideSewer                                  = 101000   ,
        UndeadBurg2OutsideBonfire                                = 101010   ,
        UndeadBurg3TaurusFogGate                                 = 101011   ,
        LowerUndeadBurg1NearLadderEntrance                       = 101100   ,
        LowerUndeadBurg2CapraFogGate                             = 101101   ,
        UndeadParish1DragonBridge                                = 101200   ,
        UndeadParish2GargoyleFogGate                             = 101210   ,
        FirelinkShrine1                                          = 102000   ,
        PaintedWorldOfAriamis1BridgeStartOfLevel                 = 110000   ,
        PaintedWorldOfAriamis2                                   = 110010   ,
        PaintedWorldOfAriamis3RedSignSoapstone                   = 110001   ,
        PaintedWorldOfAriamis4                                   = 110011   ,
        DarkrootGarden1TitaniteDemonRoom                         = 120000   ,
        DarkrootBasin1                                           = 120001   ,
        DarkrootGarden2ButterflyTower                            = 120010   ,
        DarkrootGarden3PathToWolfRing                            = 120011   ,
        DarkrootForest1ForestDoor                                = 120100   ,
        DarkrootForest2BridgeNearSif                             = 120101   ,
        SanctuaryGarden1NearBonfire                              = 121000   ,
        RoyalWood1BridgeStartOfLevel                             = 121100   ,
        RoyalWood2ArtoriasFogGate                                = 121101   ,
        RoyalWood3                                               = 121102   ,
        OolacileTownship1NearBonfire                             = 121200   ,
        OolacileTownship2NearChainedPrisoner                     = 121201   ,
        ChasmOfTheAbyss1TopOfBridgeToManus                       = 121210   ,
        ManusBossRoomArea                                        = 121340   ,
        SanctuaryGuardianBossRoomWood                            = 121350   ,
        TheCatacombs1                                            = 130000   ,
        TheCatacombs2                                            = 130010   ,
        TheCatacombs3                                            = 130011   ,
        TombOfTheGiants1                                         = 131000   ,
        TombOfTheGiants2                                         = 131001   ,
        TombOfTheGiants3                                         = 131010   ,
        TombOfTheGiants4                                         = 131011   ,
        TombOfTheGiants5                                         = 131012   ,
        TombOfTheGiants6                                         = 131013   ,
        AshLake1                                                 = 132000   ,
        Blighttown1BlighttownDoor                                = 140000   ,
        Blighttown2                                              = 140001   ,
        Blighttown3                                              = 140002   ,
        Blighttown4                                              = 140010   ,
        Blighttown5NearGreatHollow                               = 140012   ,
        Blighttown6QuelaagFogGate                                = 140011   ,
        Blighttown7ValleyOfTheDrakesFogGate                      = 140013   ,
        DemonRuins1                                              = 141000   ,
        DemonRuins2                                              = 141100   ,
        DemonRuins3                                              = 141200   ,
        LostIzalith1AboveIllusoryWallBonfire                     = 141300   ,
        LostIzalith2BedOfChaosFogGate                            = 141301   ,
        SensFortress1                                            = 150000   ,
        SensFortress2                                            = 150011   ,
        SensFortress3                                            = 150001   ,
        SensFortress4                                            = 150010   ,
        SensFortress5PendulumBeam                                = 150012   ,
        SensFortress6Roof                                        = 150020   ,
        SensFortress7IronGolemFogGate                            = 150021   ,
        AnorLondo1FirstGargoyle                                  = 151000   ,
        AnorLondo2MainEntranceDoors                              = 151010   ,
        AnorLondo3BeforeSilverKnightArchers                      = 151011   ,
        AnorLondo4SolaireBonfire                                 = 151020   ,
        AnorLondo5Roof                                           = 151021   ,
        AnorLondo6OandSFogGate                                   = 151022   ,
        NewLondoRuins1FirelinkElevator                           = 160100   ,
        NewLondoRuins2Building1NearBanshee                       = 160101   ,
        NewLondoRuins3Building2CursbiteRing                      = 160110   ,
        NewLondoRuins4WalkwayToDrainLever                        = 160111   ,
        NewLondoRuins5WoodenRoomNearDrakes                       = 160112   ,
        NewLondoRuins6BuildingWithWoodenRooms                    = 160120   ,
        NewLondoRuins7FourKingsFogGate                           = 160121   ,
        TheDukesArchives1                                        = 170000   ,
        TheDukesArchives2                                        = 170001   ,
        TheDukesArchives3                                        = 170010   ,
        CrystalCave1                                             = 170011   ,
        KilnOfTheFirstFlame1LevelEntrance                        = 180000   ,
        KilnOfTheFirstFlame2SecondBlackKnight                    = 180001   ,
        KilnOfTheFirstFlame3GwynFogGate                          = 180002   ,
        NonInvadeableArea                                        = -2       ,
        GapingDragonBossRoom                                     = -12      ,
        GargoylesBossRoom                                        = -13      ,
        CrossbreedPriscillaBossRoom                              = -14      ,
        SifBossRoom                                              = -15      ,
        PinwheelBossRoom                                         = -16      ,
        GravelordNitoBossRoom                                    = -17      ,
        QuelaagBossRoom                                          = -19      ,
        BedOfChaosBossRoom                                       = -20      ,
        IronGolemBossRoom                                        = -21      ,
        OandSBossRoom                                            = -22      ,
        FourKingsBossRoom                                        = -23      ,
        SeathBossRoom                                            = -24      ,
        GwynBossRoom                                             = -25      ,
        AsylumDemonBossRoom                                      = -26      ,
        TaurusDemonBossRoom                                      = -11010911,
        CapraDemonBossRoom                                       = -11010912,
        MoonlightButterflyBossRoom                               = -11200910,
        SanctuaryGuardianBossRoom                                = -11210010,
        ArtoriasBossRoom                                         = -11210011,
        ManusBossRoom                                            = -11210012,
        KalameetBossRoom                                         = -11210014,
        DemonFiresageBossRoom                                    = -11410420,
        CeaselessDischargeBossRoom                               = -11410910,
        CentipedeDemonBossRoom                                   = -11410911,
        StrayDemonBossRoom                                       = -11810910,

    }
}
