name: Qodana
on:
  #schedule:
  #  - cron: "30 1 * * *"
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  qodana:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
