name: sign artifacts
on: workflow_dispatch 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get version
        run: |
            $version = select-xml -path "Directory.Build.props" -xpath "//PropertyGroup//Version" | Select-Object  -ExpandProperty Node | Select-Object -ExpandProperty '#text'
            echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: setup dotnet
        uses: actions/setup-dotnet@v3

      - name: dotnet restore
        run: dotnet restore

      - name: Build solution
        run: dotnet build -c release

        #Collect all the artifacts and publish them
      - name: collect artifacts
        run: |
            mkdir unsigned-artifact
            mkdir unsigned-artifact\CliTimer
            mkdir signed-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\SoulSplitter.dll                unsigned-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\SoulMemory.dll                  unsigned-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\MaterialDesignColors.dll        unsigned-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\MaterialDesignThemes.Wpf.dll    unsigned-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\Microsoft.Xaml.Behaviors.dll    unsigned-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\soulmods_x86.dll                unsigned-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\soulmods_x64.dll                unsigned-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\soulmemory_rs_x86.dll           unsigned-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\soulmemory_rs_x64.dll           unsigned-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\launcher_x86.exe                unsigned-artifact
            copy src\SoulSplitter\bin\x64\Release\net481\launcher_x64.exe                unsigned-artifact
            copy LICENSE                                                                 unsigned-artifact
            copy src\SoulMemory\bin\x64\Release\*.nupkg                                  unsigned-artifact
            copy src\CliTimer\bin\x64\release\net481\CliTimer.exe                        unsigned-artifact\CliTimer
            copy src\CliTimer\bin\x64\release\net481\CliTimer.exe.config                 unsigned-artifact\CliTimer
            copy src\CliTimer\bin\x64\release\net481\SoulMemory.dll                      unsigned-artifact\CliTimer
            copy src\CliTimer\bin\x64\release\net481\soulmods_x86.dll                    unsigned-artifact\CliTimer
            copy src\CliTimer\bin\x64\release\net481\soulmods_x64.dll                    unsigned-artifact\CliTimer

      - name: publish unsigned artifacts
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-artifact
          path: unsigned-artifact

      - name: sign artifacts with signpath
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: 187fb143-2898-4637-81fe-4f4cb599f1ff
          project-slug: SoulSplitter
          signing-policy-slug: release-signing
          github-artifact-id: ${{ steps.upload-unsigned-artifact.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: signed-artifact
          parameters: |
            version: ${{ toJSON(env.VERSION) }}

      - name: publish signed artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VERSION }}
          path: signed-artifact
