[package]
name = "soulmemory-rs-launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soulmemory-rs = { path = "../soulmemory-rs" }
mem-rs = "0.1.3"
#mem-rs = { path="C:/projects/mem-rs" }